### PR TITLE
feat(CG-1169): add azure user-check-1 rule

### PR DESCRIPTION
**Pull request by zhouse51**

### CODE REVIEW

**Review by tyler-dunkel — APPROVED** [review]

**Comment by tyler-dunkel** [comment]
conflicts needs to be resolved for this one

**Comment by zhouse51** [comment]
conflict resolved

**Comment by tyler-dunkel** [comment]
sorry needs conflicts resolved again. Damn readme!

**Comment by zhouse51** [comment]
@tyler-dunkel conflicts resolved.

**Pull request merged**
