### PR TITLE
fix(CG-1328): fix the AWS CIS 1.4.0 2.1.5 rule

### PR DESCRIPTION
**Pull request by zhouse51**

### CODE REVIEW

**Review by m-pizarro — COMMENTED** [review]
LGTM. Only a question, the equivalent rules of the others benchmarks, shouldn't they be updated? And please update the readme file.

**Comment by zhouse51** [comment]
Hi @m-pizarro , Thanks for the review. I have update the README.
Regarding to the fix in other versions, I checked with Anabella. She told me just do the fix for the CIS 1.4.0 for now. Same to the other rule fixes as well.

**Comment by m-pizarro** [comment]
> .

ah ok, don't worry, it's ok to me.

**Review by m-pizarro — APPROVED** [review]
LGTM

**Pull request merged**
