### PR TITLE
fix: Added required fields to fulfill aws schemas

### PR DESCRIPTION
**Pull request by mfranceschit**
- Required changes to enable new RulesEngine optimization.
- Included `cgId` as part of the extraFields for `aws` benchmarks.

### CODE REVIEW

**Review by hjaraujof — APPROVED** [review]

**Comment by tyler-dunkel** [comment]
tell me more about the need for this change

**Comment by mfranceschit** [comment]
> tell me more about the need for this change

Essentially, the optimization needs to know about the required ids to establish a connection between the finding and the resource. For providers like `GCP` or `azure` we don't have this problem because we always use the id field as the only identifier at Dgraph. However, in AWS, this depends on the service. We are using the id, for others, the ARN, and the cgId for a few cases. That's why the need of standardized our AWS schemas using a base schema as we have shown [here](https://github.com/cloudgraphdev/cloudgraph-provider-aws/pull/4)

**Comment by tyler-dunkel** [comment]
> > tell me more about the need for this change
> 
> Essentially, the optimization needs to know about the required ids to establish a connection between the finding and the resource. For providers like `GCP` or `azure` we don't have this problem because we always use the id field as the only identifier at Dgraph. However, in AWS, this depends on the service. We are using the id, for others, the ARN, and the cgId for a few cases. That's why the need of standardized our AWS schemas using a base schema as we have shown [here](https://github.com/cloudgraphdev/cloudgraph-provider-aws/pull/4)

Would this change no longer be needed if we make the changes we are discussing on the aws provider?

**Comment by mfranceschit** [comment]
> > > tell me more about the need for this change
> > 
> > 
> > Essentially, the optimization needs to know about the required ids to establish a connection between the finding and the resource. For providers like `GCP` or `azure` we don't have this problem because we always use the id field as the only identifier at Dgraph. However, in AWS, this depends on the service. We are using the id, for others, the ARN, and the cgId for a few cases. That's why the need of standardized our AWS schemas using a base schema as we have shown [here](https://github.com/cloudgraphdev/cloudgraph-provider-aws/pull/4)
> 
> Would this change no longer be needed if we make the changes we are discussing on the aws provider?

That's right if we stick with only one id per schema these changes won't be necessary. Although, we still have to add extra fields as the arn and account fields to the AWS benchmarks. Nonetheless, those are minor changes because it only affects two files.

**Review by tyler-dunkel — APPROVED** [review]

**Pull request merged**
